### ISSUE TITLE
Namespace missing in 17. Setting up SLI provider in Dynatrace Full Tour

### ISSUE THREAD

**Issue by jmbrinkman** [keptn/tutorials#102]
Under 17 the first command that creates the sli service misses the namespace argument: 

kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/dynatrace-sli-service/0.7.0/deploy/service.yaml 

shoud be 

kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/dynatrace-sli-service/0.7.0/deploy/service.yaml -n keptn

**Comment by jetzlstorfer** [comment]
Thanks @jmbrinkman for bringing this up.
I believe the error is in this file: https://github.com/keptn/tutorials/blob/master/site/tutorials/snippets/07/monitoring/install-sli-provider-dynatrace.md 

Would you mind fixing it a create PR? Thanks!
