### ISSUE TITLE
Dynatrace tutorial: Add information about the environment/tenant URL in Gather Dynatrace tokens step

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/tutorials#115]
I just ran into a stupid mistake: I configured my DT_TENANT as `something.my-host.com/` (mind the trailing slash).

This unfortunately lead to a misconfigured oneagent, which only gave me a weird error message that I could not deal with.

I propose that we make this clear in our docs with an example or by documenting that the URL must not have a trailing slash.

**Comment by jetzlstorfer** [comment]
It is documented in Step 9 of the Tutorial: 
https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace-07/index.html?index=..%2F..index#8 

Do you feel we need more documentation on it or a troubleshooting guide?

**Comment by christian-kreuzberger-dtx** [comment]
I think we should add that it must not have a trailing slash (which is a very common mistake when copy pasting).

**Comment by jetzlstorfer** [comment]
Right now it is highlighted like this:
![image](https://user-images.githubusercontent.com/7677092/104197394-426e9a80-5425-11eb-9f3b-85c3b3672381.png)

Should we mention it directly in step 3 of the instructions with an example of a correct ID and an incorrect one?

**Comment by christian-kreuzberger-dtx** [comment]
My bad... When I wrote the issue, I must have overlooked that part (maybe as it is below the export commands).
