### ISSUE TITLE
Keptn in a box Instructions Possible typo

### ISSUE THREAD

**Issue by wingatekr** [keptn/tutorials#133]
Following these instruction: https://tutorials.keptn.sh/tutorials/keptn-in-a-box-08/#8 
New to linux, but found this odd looking.
`sudo bash -c './keptn-in-a-box.sh &' ` 
Running as is did not work. I was going to tweet for access to the slack channel, but tried running it without the **&** before the closing ', and it seems to be working. 

According to my googling the below should be what the documentation says. 
`sudo bash -c './keptn-in-a-box.sh '  & `

**Comment by jetzlstorfer** [comment]
We need to verify this again as the problem popped up during an installation.

See also https://github.com/keptn/tutorials/pull/151

**Comment by jetzlstorfer** [comment]
Merged #151 as the fix did actually break it.

**Comment by jetzlstorfer** [comment]
Explanation why the ampersand has to be inside the string https://github.com/keptn/tutorials/pull/151#issue-615939602
