### ISSUE TITLE
Add spellcheck

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/tutorials#141]
Similar to the spellcheck in the keptn/keptn repo, we want to add spell checks to the tutorial repo.

**Comment by jetzlstorfer** [comment]
Maybe @jsoref can help here.

**Comment by jsoref** [comment]
Try copying the contents of https://github.com/check-spelling/spell-check-this/tree/prerelease/.github as a starting point? It should give you a reasonable baseline.

**Comment by jetzlstorfer** [comment]
Great, thanks! Will do so

**Comment by jetzlstorfer** [comment]
Rather than excludes, I would like to include ONLY files with extension `.md` in this folder: https://github.com/keptn/tutorials/tree/master/site/tutorials 
How could we achieve this the easiest?

**Comment by jsoref** [comment]
you can do
`^site/tutorials/.*\.md$` in the `only.txt` file

**Comment by jsoref** [comment]
Please let me know if there's a way that the repository above could have helped you figure that out. I want this to be as smooth as possible for the next person.

I'm actively thinking about what to put in advice. I think I want it to suggest patterns... – possibly linking straight to the examples for both patterns and excludes, possibly just to a wiki page for "what should I do?"

**Comment by jetzlstorfer** [comment]
Hi @jsoref 
I've now added the spellcheck bot: https://github.com/keptn/tutorials/pull/142 

However, the experience is not 100% frictionless. As you can see in the first comment by the bot, it came up with a LOT of typo-suggestions. Even technical terms such as http are included (I know, the correct spelling is HTTP but in some code parts is still referenced as http)

I know added around 250 words to the `allow.txt` file but still there are a lot of terms that are listed by the bot.
This is actually my main concern: how to make it frictionless for the user? 
For example, Kubernetes creates a lot of arbitrary IDs:
```
 NAME                                           READY   STATUS             RESTARTS   AGE
  dynatrace-oneagent-operator-7f477bf78d-dgwb6   1/1     Running            0          8m21s
  oneagent-b22m4                                 0/1     Error              6          8m15s
  oneagent-k7jn6                                 0/1     CrashLoopBackOff   6          8m15s
```
Have a look at `dynatrace-oneagent-operator-7f477bf78d-dgwb6` for example. The bot says `dgwb` is not a real word, and that is true for a fact. However, in this context, it was not meant to be a real word. This should be improved in the bot.

In general, I love the idea of having my code spell-checked when I push it!

**Comment by jsoref** [comment]
## http

This is on my todo list as [Area-dictionaries](https://github.com/check-spelling/check-spelling/wiki/Feature%3A-Area-dictionaries)

I also intend to make a newer dictionary where I might just include a bunch of technical terms. See [Archaic words](https://github.com/check-spelling/check-spelling/wiki/Archaic-words) for some of my thoughts (as I want to also slim down the dictionary at least a bit).

## pod names

So, I've looked at pod names and have not come up w/ a good way to handle them.

You could cheat here and do something like this in `patterns.txt`:

```
^\s+[-0-9a-z]+\s+\d+/\d+
```
Or
```
^\s+[-0-9a-z]+\s+\d+/\d+\s+(?:Running|Error|CrashLoopBackOff)
```
(Adding extra states)

This would work fine for the listings. But it wouldn't cover cases where someone talks about a specific pod.

You could add:

```
(?:[a-z]+){1,3}(?:-[0-9a-f]{10})?-[0-9a-z]{5}
```

Which might work.

I've definitely tried writing rules for these in places.

I'm slowly assembling patterns into: https://github.com/check-spelling/check-spelling/wiki/Configuration-Examples:-patterns but I don't think I've currently included a pod one. It's somewhere in my collective forks.

I need to write a script that gathers all of them so I can do more updates.

But it's currently lower on the todo list than some other things in [Possible features](https://github.com/check-spelling/check-spelling/wiki/Possible-features).

## collapsing comments

This is on my [todo list](https://github.com/check-spelling/check-spelling/wiki/Feature:-Collapse-older-check-comments). I have the bot doing that in the talk-to-bot mode for the single comment pair. It would be possible to have the bot do it for the most recent previous comment by itself (or risk crawling through all comments and doing it for all of them).

**Comment by mowies** [comment]
The keptn team decided to not use the check-spelling GH action anymore.
Closing this.
