### ISSUE TITLE
keptn.public.demo.keptn.sh shows `no healthy upstream`

### ISSUE THREAD

**Issue by adri** [keptn/tutorials#185]
[This page](https://tutorials.keptn.sh/tutorials/keptn-public-demo-08/index.html#0) mentions https://keptn.public.demo.keptn.sh/ but when I try to access it it shows 

```
no healthy upstream
```

**Comment by christian-kreuzberger-dtx** [comment]
Works right now - has already been fixed, so I'll close this issue.
