### ISSUE TITLE
Typo in tutorial keptn-multistage-qualitygates

### ISSUE THREAD

**Issue by ngauje** [keptn/tutorials#186]
Hello, on this page : https://tutorials.keptn.sh/tutorials/keptn-multistage-qualitygates-09/index.html?index=..%2F..index#9
the commands to add ressources are bad

We created a service named **helloserver**, and in the `keptn add-resource` we specify a service named **helloservice**

Bad:
```
keptn add-resource --project=pod-tato-head --stage=hardening --service=helloservice --resource=jmeter/load.jmx --resourceUri=jmeter/load.jmx
keptn add-resource --project=pod-tato-head --stage=hardening --service=helloservice --resource=jmeter/jmeter.conf.yaml --resourceUri=jmeter/jmeter.conf.yaml
```

Good:
```
keptn add-resource --project=pod-tato-head --stage=hardening --service=helloserver --resource=jmeter/load.jmx --resourceUri=jmeter/load.jmx
keptn add-resource --project=pod-tato-head --stage=hardening --service=helloserver --resource=jmeter/jmeter.conf.yaml --resourceUri=jmeter/jmeter.conf.yaml
```

**Comment by ngauje** [comment]
Wait...
Maybe it would be easier to switch all the helloserver references to **helloservice** since it's the name of the pod-tato-head (ie https://github.com/cncf/podtato-head/blob/main/delivery/keptn/helm-charts/helloserver/templates/service.yaml)

**Comment by TannerGabriel** [comment]
@christian-kreuzberger-dtx Can this be closed?

**Comment by christian-kreuzberger-dtx** [comment]
Don't think it's needed any longer, I'm closing it.
