### ISSUE TITLE
Keptn Full Tour on Prometheus v10 version issues

### ISSUE THREAD

**Issue by braghettos** [keptn/tutorials#202]
Hi everyone,

I'm following this tutorial: https://tutorials.keptn.sh/tutorials/keptn-full-tour-prometheus-09 but I think there are a lot of issues regarding versions of repositories.

Let me describe the issues:
- STEP 8: this is the command suggested: `git clone --branch release-0.10.0 https://github.com/keptn/examples.git --single-branch` but in the repo I can find the branch https://github.com/keptn/examples/tree/release-0.9.1. Which one should I use?
- STEP 13: this is the command suggeste: `kubectl apply -f https://raw.githubusercontent.com/keptn-contrib/prometheus-service/release-0.6.1/deploy/role.yaml -n monitoring` but in the repo I can find the release 0.7.0 that states _This release adapts components to support the auto-remediation use case with Keptn._. Which one should I use?

Is this tutorial focused on Keptn 0.9 or 0.10?

Thanks for any feedback!

**Comment by johannes-b** [comment]
@braghettos the link you referenced in the first sentence refers to a tutorial for Keptn 0.9. 

Are you using 0.10?

**Comment by braghettos** [comment]
@johannes-b I'm using Keptn 0.9.0
