### ISSUE TITLE
Missing step to actually install Prometheus

### ISSUE THREAD

**Issue by 90lantran** [keptn/tutorials#207]
https://tutorials.keptn.sh/tutorials/keptn-argo-cd-deployment-07/index.html?index=..%2F..keptn07x#5
I cannot find this tutorial in this repo, but this is the link.
The step I mentioned above missed a step to actually install Prometheus which should be before step1.
The version of step1 for Prometheus-service and step2 for Prometheus SLI provider are out of date.

**Comment by oleg-nenashev** [comment]
AFAICT the tutorial was rewritten later for 0.9.0: https://tutorials.keptn.sh/tutorials/keptn-argo-rollouts-dynatrace-09-on-k3s/index.html?index=..%2F..keptn09x#0 . Not sure the one in 0.7.0 is still relevant
