### ISSUE TITLE
Archive Old Tutorials on tutorials.keptn.sh

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/tutorials#237]
The tutorials in this repository are dated, but still include some potentially useful content. We would like to stop using the current engine, because it is:

- Tutorials are not applicable to the upcoming LTS release
- Obsolete codelab version
- Private scripts used to build the tutorials page
- Bad user experience

## TODOs

https://github.com/keptn/tutorials/issues/237#tasklist-block-4796e50f-891a-48e3-9fce-617b02ea7db1

**Comment by StackScribe** [comment]
We didn't get much response to our attempt to review the old tutorials so, early in November 2022, @aepfli archived everything except the Killrcoda end-to-end tutorial.  The Litmus Chaos people did step up and updated their tutorial so the new version is being restored to the Tutorials page.  The others are gone unless someone wants to take ownership and I am closing this issue.
