### ISSUE TITLE
eksctl hyperlink returns 404

### ISSUE THREAD

**Issue by gabrielprioli** [keptn/tutorials#27]
On https://tutorials.keptn.sh/tutorials/keptn-installation-eks/index.html?index=..%2F..index#2 the hyperlink on "eksctl" returns 404. The sentence is: "Sample script using eksctl to create such a cluster"

old url: https://eksctl.io/introduction/installation/
new url: https://eksctl.io/introduction/

**Comment by jetzlstorfer** [comment]
Thanks @gabrielprioli for mentioning this. It is now fixed.
