### ISSUE TITLE
Remove "Configure maintenance windows" from list of permissions

### ISSUE THREAD

**Issue by gabrielprioli** [keptn/tutorials#28]
That token scope was used when the maintenance window endpoints used to be in the Environment API, but now they are in the Configuration API so the Read/Write Configuration scope is enough and the "Configure maintenance windows" scope doesn't exist anymore.

Tutorials page:
https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace/index.html?index=..%2F..index#3

**Comment by jetzlstorfer** [comment]
Hi @gabrielprioli 

I've looked on the list and I assume this one would be the updated one:

- Access problem and event feed, metrics and topology
- Read configuration
- Write configuration
- Capture request data
- Real user monitoring JavaScript tag management

What do you think?

**Comment by gabrielprioli** [comment]
In your list you didn't include "Access logs". Does keptn need a token with the logs scope?

**Comment by jetzlstorfer** [comment]
We have figured it out and the list of permissions has been updated with #35 - thanks for catching it!
