### ISSUE TITLE
Link update needed

### ISSUE THREAD

**Issue by gabrielprioli** [keptn/tutorials#36]
Hello team, I come to report a link that needs to be updated in the tutorial "Keptn Full Tour on Dynatrace".

Page: https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace/index.html?index=..%2F..index#6
Sentence: "Onboard the carts service using the keptn onboard service command:"

Old link: https://keptn.sh/docs/0.6.0/reference/cli/#keptn-onboard-service
New link: https://keptn.sh/docs/0.6.0/reference/cli/commands/keptn_onboard_service/

**Comment by jetzlstorfer** [comment]
fixed in #37
