### ISSUE TITLE
Keptn Full Tour: View Carts Service

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/tutorials#73]
I just stumbled across this step of the tutorial for Keptn 0.7.x:

![Screenshot from 2020-09-11 14-23-27](https://user-images.githubusercontent.com/56065213/92925222-75cef780-f43a-11ea-943f-d96700bb3929.png)

In theory, the above commands will work with the tutorial. However, this will only work if the CD part is on the same cluster and behind the same ingress as the api (for the tutorial, this is obviously true).

Keptn offers a more generic way, by configuring the protocol, hostname and port as specified here: https://keptn.sh/docs/0.7.x/continuous_delivery/expose_services/#create-configmap-with-ingress-information

Maybe we could use the configmap in the tutorial?

Another way that we can also use to teach the user how Keptn works is the `keptn get event` command:
```console
$ keptn get event sh.keptn.events.deployment-finished --project sockshop --service carts --stage dev

{
    "contenttype": "application/json",
    "data": {
        "deploymentURILocal": "http://carts.sockshop-dev",
        "deploymentURIPublic": "http://carts.sockshop-dev.1-2-3-4.nip.io:80",
        "deploymentstrategy": "direct",
        "image": "docker.io/keptnexamples/carts",
        "labels": null,
        "project": "sockshop",
        "service": "carts",
        "stage": "dev",
        "tag": "0.11.1",
        "teststrategy": "functional"
    },
    "id": "3077338f-82e1-4301-92c8-f2983139c200",
    "shkeptncontext": "069d758a-9b76-45a9-af5f-a6e9b42e391e",
    "source": "helm-service",
    "specversion": "0.2",
    "time": "2020-09-11T12:21:22.444Z",
    "type": "sh.keptn.events.deployment-finished"
}

```

**Comment by jetzlstorfer** [comment]
good point @christian-kreuzberger-dtx ! 

The purpose of the tutorial is to execute in the exact way we've written it. If the user wants to change ingress, name of project etc this means the user has to take care of all subsequent commands to be correct and I'd assume the user has to work then rather with the documentation than with the tutorial.

But back to your point: 
- how could we use the configmap? Do you refer to the `ingress-config` or the `api-nginx-config`? 
- The CLI command makes sense, maybe that's the best way to do it...

**Comment by christian-kreuzberger-dtx** [comment]
Just verified this with Keptn 0.8.2, you can get the public URL of a deployed service by inspecting the `deployment.finished` event, e.g.:

```console
keptn get event sh.keptn.event.deployment.finished --project sockshop --service carts --stage dev | jq -r '.[0].data.deployment.deploymentURIsPublic'
```

The description is as follows:

* `keptn get event` - Keptn CLI command to fetch events
* `sh.keptn.event.deployment.finished` - specify which event
* `--project sockshop --service carts --stage dev` - specify project, service and stage
* `|` - bash pipe operator
* `jq` - tool to parse and process json output
* `-r '.[0].data.deployment.deploymentURIsPublic'` - parse the latest deployments deploymentURIsPublic

**Comment by christian-kreuzberger-dtx** [comment]
I'm unassigning Juergen, this issue still needs some work
