### ISSUE TITLE
Error in keptn quality-gates with dynatrace tutorial

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/tutorials#81]
From https://tutorials.keptn.sh/tutorials/keptn-quality-gates-dynatrace-07/index.html?index=..%2F..index#8

![Screenshot from 2020-10-07 16-02-01](https://user-images.githubusercontent.com/56065213/95341361-767e7080-08b6-11eb-957e-b7ce827dc31e.png)

The command
```
git clone --branch release-0.7.0 https://github.com/keptn/examples.git --single-branch

cd examples/simplenodeservicequality-gate-only
```

fails with

```
bash: cd: examples/simplenodeservicequality-gate-only: No such file or directory
```

I believe the command should be
```
cd examples/simplenodeservice/quality-gate-only
```

In addition, it should checkout the release-0.7.1 (or 0.7.2 branch soon).

**Comment by jetzlstorfer** [comment]
@grabnerandi can you take care of this?

**Comment by grabnerandi** [comment]
Yep - I will redo the quality gate anyway as I will start using the new https://github.com/keptn-sandbox/keptn-on-k3s/tree/dynatrace-support as the starting point

**Comment by christian-kreuzberger-dtx** [comment]
This issue is no longer present, closing it.
