### ISSUE TITLE
Self-healing with Unleash tutorial: Unleash flips the feature flag in all stages the carts service is running

### ISSUE THREAD

**Issue by johannes-b** [keptn/tutorials#86]
When running the self-healing tutorial with Unleash, the tutorial is set up in a way that there is no distinction between the stages. This means that changing the feature flag (e.g., EnablePromotion) in Unleash has an impact on all *carts services* running the different stages (dev, staging). 

**Task**
- Add a note to the tutorial that Unleash has an impact on all stages and this is not a production-like approach. The Unleash-pro version provides support on that use-case.

**Comment by jetzlstorfer** [comment]
Thanks @johannes-b for bringing this up. Very valid point.
What is done in the tutorials to mitigate this, is to only generate traffic for the `production` stage of the `carts` service.
See step 5 here: https://tutorials.keptn.sh/tutorials/keptn-full-tour-dynatrace-07/index.html?index=..%2F..index#25 

However, I'll add a comment on how it actually works to clarify this.
